---
language: java
jdk:
    - oraclejdk8
before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
cache:
  - $HOME/.m2
install: mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V

