---
language: java
jdk:
    - oraclejdk8
    - oraclejdk7
before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V

